kibot:
  version: 1

outputs:
  - name: edge_cut
    comment: Plate edge cut
    type: dxf
    options:
      metric_units: true
      polygon_mode: false
      use_aux_axis_as_origin: true
    layers:
       - Edge.Cuts

  - name: drill_notes
    comment: Fabrication notes
    type: pcb_print
    options:
      pages:
        layers:
           - Edge.Cuts
           - User.1

  - name: 'step'
    comment: "PCB STEP file"
    type: step
    options:
      min_distance: 0.01

  - name: pcb_top_g
    comment: "2D Renders - top"
    type: pcbdraw
    options:
      output: "%f-%i.%x"
      format: jpg
      show_components: none
      dpi: 600

  - name: JLCPCB_gerbers
    comment: Gerbers compatible with JLCPCB
    type: gerber
    dir: gerber
    options: &gerber_options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      line_width: 0.1
      subtract_mask_from_silk: true
      inner_extension_pattern: '.gp%n'
    layers:
      # Note: a more generic approach is to use 'copper' but then the filenames
      # are slightly different.
      - F.Cu
      - B.Cu
      - In1.Cu
      - In2.Cu
      - In3.Cu
      - In4.Cu
      - In5.Cu
      - In6.Cu
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts

  - name: JLCPCB_drill
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: gerber
    options:
      pth_and_npth_single_file: false
      pth_id: '-PTH'
      npth_id: '-NPTH'
      metric_units: true
      map: gerber
      route_mode_for_oval_holes: false
      output: "%f_%i.%x"

  - name: gerber
    comment: ZIP file for JLCPCB
    type: compress
    options:
      output: "%f-%i.%x"
      files:
        - from_output: JLCPCB_gerbers
          dest: /
        - from_output: JLCPCB_drill
          dest: /

